Traceback (most recent call last):
  File "/usr/local/pyenv/versions/3.10.10/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/local/pyenv/versions/3.10.10/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/pyenv/versions/3.10.10/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/local/pyenv/versions/3.10.10/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/local/pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/local/pyenv/versions/3.10.10/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/usr/local/pyenv/versions/3.10.10/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/local/pyenv/versions/3.10.10/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
workflow.execute_entity_task(tasks.run_random_climate, gdirs, nyears=100,
                             y0=2009, halfsize=10, output_filesuffix='_2000')
ds2000 = utils.compile_run_output(gdirs, filesuffix='_2000')
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[16], line 3[0m
[1;32m      1[0m workflow[38;5;241m.[39mexecute_entity_task(tasks[38;5;241m.[39mrun_random_climate, gdirs, nyears[38;5;241m=[39m[38;5;241m100[39m,
[1;32m      2[0m                              y0[38;5;241m=[39m[38;5;241m2009[39m, halfsize[38;5;241m=[39m[38;5;241m10[39m, output_filesuffix[38;5;241m=[39m[38;5;124m'[39m[38;5;124m_2000[39m[38;5;124m'[39m)
[0;32m----> 3[0m ds2000 [38;5;241m=[39m [43mutils[49m[38;5;241;43m.[39;49m[43mcompile_run_output[49m[43m([49m[43mgdirs[49m[43m,[49m[43m [49m[43mfilesuffix[49m[38;5;241;43m=[39;49m[38;5;124;43m'[39;49m[38;5;124;43m_2000[39;49m[38;5;124;43m'[39;49m[43m)[49m

File [0;32m/usr/local/pyenv/versions/3.10.10/lib/python3.10/site-packages/oggm/utils/_workflow.py:550[0m, in [0;36mglobal_task.__call__.<locals>._global_task[0;34m(gdirs, **kwargs)[0m
[1;32m    546[0m [38;5;28mself[39m[38;5;241m.[39mlog[38;5;241m.[39mworkflow([38;5;124m'[39m[38;5;124mApplying global task [39m[38;5;132;01m%s[39;00m[38;5;124m on [39m[38;5;132;01m%s[39;00m[38;5;124m glaciers[39m[38;5;124m'[39m,
[1;32m    547[0m                   task_func[38;5;241m.[39m[38;5;18m__name__[39m, [38;5;28mlen[39m(gdirs))
[1;32m    549[0m [38;5;66;03m# Run the task[39;00m
[0;32m--> 550[0m [38;5;28;01mreturn[39;00m [43mtask_func[49m[43m([49m[43mgdirs[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m

File [0;32m/usr/local/pyenv/versions/3.10.10/lib/python3.10/site-packages/oggm/utils/_workflow.py:964[0m, in [0;36mcompile_to_netcdf.__call__.<locals>._compile_to_netcdf[0;34m(gdirs, input_filesuffix, output_filesuffix, path, tmp_file_size, **kwargs)[0m
[1;32m    961[0m [38;5;66;03m# Run the task[39;00m
[1;32m    962[0m [38;5;66;03m# If small gdir size, no need for temporary files[39;00m
[1;32m    963[0m [38;5;28;01mif[39;00m [38;5;28mlen[39m(gdirs) [38;5;241m<[39m tmp_file_size [38;5;129;01mor[39;00m [38;5;129;01mnot[39;00m path:
[0;32m--> 964[0m     [38;5;28;01mreturn[39;00m [43mtask_func[49m[43m([49m[43mgdirs[49m[43m,[49m[43m [49m[43minput_filesuffix[49m[38;5;241;43m=[39;49m[43minput_filesuffix[49m[43m,[49m
[1;32m    965[0m [43m                     [49m[43mpath[49m[38;5;241;43m=[39;49m[43mpath[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m
[1;32m    967[0m [38;5;66;03m# Otherwise, divide and conquer[39;00m
[1;32m    968[0m sub_gdirs [38;5;241m=[39m [gdirs[i: i [38;5;241m+[39m tmp_file_size] [38;5;28;01mfor[39;00m i [38;5;129;01min[39;00m
[1;32m    969[0m              [38;5;28mrange[39m([38;5;241m0[39m, [38;5;28mlen[39m(gdirs), tmp_file_size)]

[0;31mTypeError[0m: compile_run_output() got an unexpected keyword argument 'filesuffix'
TypeError: compile_run_output() got an unexpected keyword argument 'filesuffix'

